version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: ibmcom/db2
    hostname: db2server
    container_name: db2server
    restart: always
    privileged: true
    ports:
      - "50000:50000"
    volumes:
      - ./database:/database
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'su - db2inst1 -c "db2 connect to db2_data user db2inst1 using ${DB2INST1_PASSWORD}"',
        ]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  db2_data:
