version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    env_file:
      - .env
    image: ibmcom/db2
    ports:
      - "50000:50000"
    volumes:
      - db2_data:/home/alex/projects/python_coding/django-drf-app/database
    healthcheck:
      test: "nc -z localhost 50000"
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  db2_data:
